### ISSUE TITLE
Working with large OpenAPI files

### ISSUE THREAD

**Issue by jaredmoody** [notEthan/scorpio#152]
Hi @notEthan!

I'm evaluating using scorpio for a work project and got stuck pretty early. The OpenAPI JSON document I'm wanting to consume is quite large -  6.6MB of JSON 😳 - and just trying to load this class hangs indefinitely.

```
module ConnectWise
  class Resource < Scorpio::ResourceBase
    self.openapi_document = JSON.load(Rails.root.join('docs/connect_wise.json'))
  end
end

```

I assume Scorpio is trying to generate a lot of code at once when that's loaded. 

Do you have general recommendations here? I only need a small subset of the API that the document defines - should I delete everything from the OpenAPI document I'm not using? Is there something I could do differently to lazy-load/generate only what I need?

Thanks!

**Comment by notEthan** [comment]
Unfortunately, the poor performance of Scorpio (really JSI, but effectively both) on large documents is one of the two big hurdles I'm working through before declaring these libraries as v1.0 production-ready things. I have a rough prototype working that fixes this and makes performance many orders of magnitude better. But at the moment it is only a prototype and needs a good bit more work before being generally usable. It's getting there, but I am not so good at estimating the time it will take to be ready for release.

**Comment by notEthan** [comment]
That took longer than expected. I have gotten this to a much better place, as of release v0.6.4.

Working with an 11 MB openapi document (860 operations; 229,000 nodes in the document):

Before:

iterating each operation (first time): 9.5 seconds
iterating each operation (second time): 7.1 seconds
iterating each node of the document (first time): 995 seconds
iterating each node of the document (second time): 246 seconds

Now:

iterating each operation (first time): 0.36 seconds
iterating each operation (second time): 0.014 seconds
iterating each node of the document (first time): 166 seconds
iterating each node of the document (second time): 2.8 seconds


That could still be quicker. I have some further improvements in the pipeline, though they are smaller increments. For now I will consider this in an acceptable place and close.
